#!/usr/bin/env bash
# This script displays a list of currently running processes

ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,cmd --sort=user,pid --forest | awk '{print $1, $2, $3, $4, $5, $6, $7, $8, $9" "$10" "$11" "$12" "$13, $14, $15}' | head -50